name: Auto Format Code
on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Enter File to be Formatted'
        required: true
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format
        env:
          FILE_NAME: ${{ github.event.inputs.filename }}
        run: |
          sudo snap install shfmt
          shfmt -w $FILE_NAME
      - name: Commit
        run: |
          git config --global user.name 'github-actions[BOT]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -am "Format Shell Script"
          git push
